import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
        h2{
          font-size: 38px;
        }
        h3{
          font-size: 28px;
        }
        `
      }</style>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Coders Blog App
        </h1>

{/* Image component not use in static side generation */}
        {/* <Image className={styles.myimg} src='/homeimg.jpg' width={157} height={158}/> */}
        <img className={styles.myimg}  src='/homeimg.jpg'width={157} height={158} />

        <p className={styles.description}>
          A blog for coders by a coder
        </p>

        <div className="blogs">
          <h2>Popular Blog</h2>
          <div className="blog-item">
            <h3>How to learn javascript in 2022</h3>
            <p>JavaScript is the language used to design logic for the web


            </p>
          </div>
          <div className="blog-item">
            <h3>How to learn javascript in 2022</h3>
            <p>JavaScript is the language used to design logic for the web


            </p>
          </div>
          <div className="blog-item">
            <h3>How to learn javascript in 2022</h3>
            <p>JavaScript is the language used to design logic for the web


            </p>
          </div>
        </div>


      </main>
    </div>
  )
}
